/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_hwbot_cpuid_CpuId */

#ifndef _Included_org_hwbot_cpuid_CpuId
#define _Included_org_hwbot_cpuid_CpuId
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_hwbot_cpuid_CpuId
 * Method:    model
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_hwbot_cpuid_CpuId_model
  (JNIEnv *, jclass);

/*
 * Class:     org_hwbot_cpuid_CpuId
 * Method:    rdtsc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_hwbot_cpuid_CpuId_rdtsc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
